# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
references:
  workspace_root: &workspace_root
    ~/app
  pkg_directory: &pkg_directory
    ~/app/pkg
  ruby_environment: &ruby_environment
    RAILS_ENV: test
    DB: postgres
    DB_HOST: localhost
    DB_USERNAME: postgres
    CIRCLE_TEST_REPORTS: /tmp/test-results
    CIRCLE_ARTIFACTS: /tmp/test-artifacts
    COVERAGE: true
    COVERAGE_DIR: /tmp/test-artifacts/coverage
    BUNDLE_JOBS: 4
    BUNDLE_RETRY: 3
    BUNDLE_PATH: ~/app/vendor/bundle
  database_container: &database_container
    image: circleci/postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
    working_directory: *workspace_root
  elasticsearch_container: &elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    environment:
      - cluster.name: elasticsearch
      - xpack.security.enabled: false
      - transport.host: localhost
      - network.host: 127.0.0.1
      - http.port: 9200
    working_directory: *workspace_root
  ruby_container: &ruby_container
    docker:
      - image: circleci/ruby:2.6-stretch-node-browsers
        environment: *ruby_environment
      - *database_container
      - *elasticsearch_container
    working_directory: *workspace_root
  install_apt_dependencies: &install_apt_dependencies
    run:
      name: Install apt dependencies
      command: |
        sudo apt-get update -qq \
          && sudo apt-get install --no-install-recommends -y \
            libxrender1 \
            libxext6 \
            xz-utils \
            default-jre \
            imagemagick \
            poppler-utils \
            mupdf-tools \
            ffmpeg
  install_bundle_dependencies: &install_bundle_dependencies
    run:
      name: Install gem dependencies
      command: |
        gem install bundler-audit && bundle audit update
        bundle check --path=~/app/vendor/bundle || bundle install || "${ALLOW_FAILURE}" == "true"
  setup_configurations: &setup_configurations
    run:
      name: Setup configurations
      command: |
        cp config/credentials/test.yml.enc config/credentials.yml.enc
  setup_database: &setup_database
    run:
      name: Setup database
      command: |
        cp ~/app/config/database.ci.yml ~/app/config/database.yml
        ~/app/bin/bundle exec rake db:create db:migrate || "${ALLOW_FAILURE}" == "true"
  run_bundle_audit: &run_bundle_audit
    run:
      name: Run bundle audit
      command: ~/app/bin/bundle audit
  run_brakeman: &run_brakeman
    run:
      name: Run brakeman
      command: ~/app/bin/bundle exec brakeman || "${ALLOW_FAILURE}" == "true"
  run_rubocop: &run_rubocop
    run:
      name: Run rubocop lints
      command: |
        ~/app/bin/bundle exec rubocop \
        --require rubocop/formatter/junit_formatter \
        --format RuboCop::Formatter::JUnitFormatter \
        -o ${CIRCLE_TEST_REPORTS}/rubocop.xml || "${ALLOW_FAILURE}" == "true"
  run_rspec: &run_rspec
    run:
      name: Run rspec tests
      command: |
        ~/app/bin/bundle exec rspec \
        -r rspec_junit_formatter \
        --format RspecJunitFormatter \
        -o ${CIRCLE_TEST_REPORTS}/rspec.xml || "${ALLOW_FAILURE}" == "true"
  wait_for_db: &wait_for_db
    run:
      name: Wait for DB
      command: dockerize -wait tcp://localhost:5432 -timeout 1m
  wait_for_elasticsearch: &wait_for_elasticsearch
    run:
      name: Wait for Elasticsearch
      command: dockerize -wait tcp://localhost:9200 -timeout 1m
  install_yarn_packages: &install_yarn_packages
    run:
      name: Install yarn packages
      command: yarn install --cwd ~/app/
  cache_yarn_packages: &cache_yarn_packages
    save_cache:
      name: Save Yarn Package Cache
      key: v1-yarn-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn
        - ~/app/node_modules
  restore_yarn_packages: &restore_yarn_packages
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - v1-yarn-{{ checksum "yarn.lock" }}
  restore_repo: &restore_repo
    restore_cache:
      name: Restore repo Cache
      keys:
        - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
  create_coverage_directory: &create_coverage_directory
    run:
      name: Create coverage directory
      command: |
        mkdir -p ${COVERAGE_DIR}
  prepare_database: &prepare_database
    run:
      name: Prepare DB
      command: bin/rails db:schema:load --trace
  precompile_assets: &precompile_assets
    run:
      name: Precompile assets
      command: |
        rm -rf public/assets && \
        RAILS_MASTER_KEY=${RAILS_MASTER_KEY_PRODUCTION} \
        RAILS_ENV=production \
        RAILS_GROUPS=assets \
        bundle exec rake assets:precompile
  install_container_test: &install_container_test
    run:
      name: Install Container Structure Tests
      command: |
        curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 \
          && chmod +x container-structure-test-linux-amd64 \
          && mv container-structure-test-linux-amd64 \
            /usr/local/bin/container-structure-test
        container-structure-test version
        mkdir -p ${CIRCLE_TEST_REPORTS}
  test_docker_image: &test_docker_image
    run:
      name: Test docker image
      command: |
        container-structure-test test \
          --image app:latest \
          --config docker/app.yml \
          --test-report ${CIRCLE_TEST_REPORTS}/app.json
  setup_gcloud: &setup_gcloud
    run:
      name: Setup Google Cloud and environment
      command: |
        echo ${GCLOUD_SERVICE_KEY} > ${HOME}/gcloud-service-key.json && \
          gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json && \
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
  setup_gcloud_docker: &setup_gcloud_docker
    run:
      name: Setup Google Cloud for Docker
      command: |
        gcloud --quiet auth configure-docker && \
          docker login -u _json_key --password-stdin https://gcr.io < ${HOME}/gcloud-service-key.json && \
          echo 'export DOCKER_ENDPOINT="asia.gcr.io/${GOOGLE_PROJECT_ID}"' >> $BASH_ENV
  load_docker_image_layer: &load_docker_image_layer
    run:
      name: Load Docker image layer cache
      command: |
        set +o pipefail
        docker load -i /home/circleci/app.tar | true
  build_docker_image: &build_docker_image
    run:
      name: Build Docker image
      command: |
        docker build -t app \
          --cache-from=app\
          --build-arg BUILD_REVISION=${CIRCLE_SHA1} \
          --build-arg BUILD_CREATED=$(date -u +"%Y-%m-%dT%H:%M:%SZ") .
  save_docker_image_layer: &save_docker_image_layer
    run:
      name: Save Docker image layer cache
      command: docker save -o /home/circleci/app.tar app
  release_docker_image: &release_docker_image
    run:
      name: Release docker image
      command: |
        docker tag app $DOCKER_ENDPOINT:$(git rev-parse --short HEAD) && \
          docker push $DOCKER_ENDPOINT:$(git rev-parse --short HEAD)
  install_sentry: &install_sentry
    run:
      name: Install Sentry CLI
      command:  |
        curl -sL https://sentry.io/get-cli/ | bash
        sentry-cli info
  install_test_cc_reporter: &install_test_cc_reporter
    run:
      name: Install Code Climate Test Reporter
      command: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
jobs:
  checkout_code:
    <<: *ruby_container
    steps:
      - checkout
      - save_cache:
          name: Store repo cache
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - *workspace_root
  test-rails_6_0:
    parallelism: 1
    <<: *ruby_container
    steps:
      - *restore_repo
      - *restore_yarn_packages
      - restore_cache:
          name: Restore bundle cache
          keys:
            - v1-rails-6-0-bundle-{{ .Branch }}-{{ checksum "Gemfile" }}
      - *install_apt_dependencies
      - *install_bundle_dependencies
      - save_cache:
          name: Store bundle cache
          key: v1-rails-6-0-bundle-{{ .Branch }}-{{ checksum "Gemfile" }}
          paths:
            - ~/app/vendor/bundle
      - *install_yarn_packages
      - *cache_yarn_packages
      - *wait_for_db
      - *wait_for_elasticsearch
      - *setup_configurations
      - *setup_database
      - *run_bundle_audit
      - *run_brakeman
      - *run_rubocop
      - *run_rspec
      - *create_coverage_directory
      - run:
          name: Setup configurations for production
          command: |
            rm -rf config/credentials.yml.enc tmp/* log/*
            cp config/credentials/production.yml.enc config/credentials.yml.enc
      - *precompile_assets
      - store_artifacts:
          path: /tmp/test-artifacts
          destination: rails-6-0-test-artifacts
      - store_artifacts:
          path: /tmp/test-results
          destination: rails-6-0-raw-test-output
      - store_test_results:
          path: /tmp/test-results
      - persist_to_workspace:
          root: /tmp/test-artifacts
          paths:
            - coverage
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - app
  test-rails_6_0_stable:
    parallelism: 1
    <<: *ruby_container
    environment:
      RAILS_VERSION: 6-0-stable
      ALLOW_FAILURE: true
    steps:
      - *restore_repo
      - *restore_yarn_packages
      - restore_cache:
          name: Restore bundle cache
          keys:
            - v1-rails-6-0-stable-bundle-{{ .Branch }}-{{ checksum "Gemfile" }}
      - *install_apt_dependencies
      - *install_bundle_dependencies
      - save_cache:
          name: Store bundle cache
          key: v1-rails-6-0-stable-bundle-{{ .Branch }}-{{ checksum "Gemfile" }}
          paths:
            - ~/app/vendor/bundle
      - *install_yarn_packages
      - *cache_yarn_packages
      - *setup_configurations
      - *wait_for_db
      - *wait_for_elasticsearch
      - *setup_database
      - *run_bundle_audit
      - *run_brakeman
      - *run_rubocop
      - *run_rspec
      - *create_coverage_directory
      - store_artifacts:
          path: /tmp/test-artifacts
          destination: rails-6-0-test-artifacts
      - store_artifacts:
          path: /tmp/test-results
          destination: rails-6-0-raw-test-output
      - store_test_results:
          path: /tmp/test-results
      - persist_to_workspace:
          root: /tmp/test-artifacts
          paths:
            - coverage
  test-rails_master:
    parallelism: 1
    <<: *ruby_container
    environment:
      RAILS_VERSION: master
      ALLOW_FAILURE: true
    steps:
      - *restore_repo
      - *restore_yarn_packages
      - restore_cache:
          name: Restore bundle cache
          keys:
            - v1-rails-master-bundle-{{ .Branch }}-{{ checksum "Gemfile" }}
      - *install_apt_dependencies
      - *install_bundle_dependencies
      - save_cache:
          name: Store bundle cache
          key: v1-rails-master-bundle-{{ .Branch }}-{{ checksum "Gemfile" }}
          paths:
            - ~/app/vendor/bundle
      - *install_yarn_packages
      - *cache_yarn_packages
      - *wait_for_db
      - *wait_for_elasticsearch
      - *setup_configurations
      - *setup_database
      - *run_bundle_audit
      - *run_brakeman
      - *run_rubocop
      - *run_rspec
      - *create_coverage_directory
      - store_artifacts:
          path: /tmp/test-artifacts
          destination: rails-6-0-test-artifacts
      - store_artifacts:
          path: /tmp/test-results
          destination: rails-6-0-raw-test-output
      - store_test_results:
          path: /tmp/test-results
      - persist_to_workspace:
          root: /tmp/test-artifacts
          paths:
            - coverage
  send-test_coverage:
    <<: *ruby_container
    steps:
      - *restore_repo
      - attach_workspace:
          at: /tmp/test-artifacts
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - run:
          name: Setup ENVs
          command: |
            export GIT_BRANCH="$CIRCLE_BRANCH"
            export GIT_COMMIT_SHA="$CIRCLE_SHA1"
            export GIT_COMMITTED_AT="$(date +%s)"
      - run:
          name: Format test coverage
          command: |
            ./tmp/cc-test-reporter format-coverage \
              -t simplecov \
              -o tmp/codeclimate.www.json \
              ${COVERAGE_DIR}/.resultset.json
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 1 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json
  build-docker_image:
    docker:
      - image: google/cloud-sdk
        environment:
          CIRCLE_TEST_REPORTS: /tmp/test-results
      - *database_container
    working_directory: /home/circleci/app
    steps:
      - attach_workspace:
          at: /home/circleci
      - setup_remote_docker
      - restore_cache:
          name: Restore Docker image layer cache
          keys:
            - v1-docker-ruby-2.6-{{ .Branch }}-{{ checksum "Dockerfile" }}
      - *load_docker_image_layer
      - *setup_gcloud
      - *setup_gcloud_docker
      - *build_docker_image
      - *install_container_test
      - *test_docker_image
      - *save_docker_image_layer
      - save_cache:
          key: v1-docker-ruby-2.6-{{ .Branch }}-{{ checksum "Dockerfile" }}
          paths:
            - /home/circleci/app.tar
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - app.tar
            - app
  release-docker_image:
    docker:
      - image: google/cloud-sdk
    working_directory: /home/circleci/app
    steps:
      - setup_remote_docker
      - *setup_gcloud
      - *setup_gcloud_docker
      - attach_workspace:
          at: /home/circleci
      - *load_docker_image_layer
      - *release_docker_image
      - run:
          name: Release default docker image
          command: |
            docker tag app $DOCKER_ENDPOINT:latest && \
              docker push $DOCKER_ENDPOINT:latest
workflows:
  version: 2
  test-build-release:
    jobs:
      - checkout_code
      - test-rails_6_0:
          requires:
            - checkout_code
      - test-rails_6_0_stable:
          requires:
            - checkout_code
          filters:
            branches:
              only:
                - master
      - test-rails_master:
          requires:
            - checkout_code
          filters:
            branches:
              only:
                - master
      - send-test_coverage:
          requires:
            - test-rails_6_0
      - build-docker_image:
          requires:
            - test-rails_6_0
      - request-release-docker_image:
          type: approval
          requires:
            - build-docker_image
          filters:
            branches:
              only:
                - master
                - /.*-stable/
      - release-docker_image:
          requires:
            - request-release-docker_image
