default: &default
  adapter: postgresql
  username: postgres
  host: localhost
  min_messages: warning

development:
  <<: *default
  database: db_devt
test:
  <<: *default
  database: db_test
production:
  <<: *default
  database: <db_prod
